# Generated by Django 3.0.2 on 2020-01-15 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bankau',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
